---
# tasks/main.yml file for role_nutanix_prism_api
- name: Run API connection pre-checks
  ansible.builtin.include_tasks: pre_checks.yml

- name: Connect to the Nutanix API
  ansible.builtin.include_tasks: connect_api.yml
