---
# tasks/pre_checks.yml file for role_nutanix_prism_api
- name: Check role_nutanix_prism_api_host is defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_prism_api_host' must be defined."
  when:
    - role_nutanix_prism_api_host is not defined
    - role_nutanix_prism_api_host != ""

- name: Debug role_nutanix_prism_api_host
  ansible.builtin.debug:
    var: role_nutanix_prism_api_host
  when: role_nutanix_prism_api_debug

- name: Check role_nutanix_prism_api_host_username is defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_prism_api_host_username' must be defined."
  when:
    - role_nutanix_prism_api_host_username is not defined
    - role_nutanix_prism_api_host_usernamername != ""

- name: Check role_nutanix_prism_api_host_password is defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_prism_api_host_password' must be defined."
  when:
    - role_nutanix_prism_api_host_password is not defined
    - role_nutanix_prism_api_host_password != ""
